services:
  - type: web
    name: global-etf-database-api
    runtime: python
    rootDir: api-server
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /healthz
